Revert "Make class ServerConfig set a default version"
This reverts commit 3857d01803883661503fd90739eb1fbcc0224f20.

This prevents failures due to issues like so:

    Traceback (most recent call last):
      File "…/tests/foreman/api/test_syncplan.py", line 41, in test_get_routes
        org = entities.Organization().create()
      File "…/nailgun/entities.py", line 2337, in __init__
        if server_config.version >= Version('6.1.1'):  # default: True
    AttributeError: 'NoneType' object has no attribute 'version'